# Generated by Django 4.2.28 on 2026-02-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='duration_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
